### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by CaramelFur** [aditya-K2/gspt#1]
Hi there, I tried to run this program.
I logged in with the URL it gave me, this seemed successful.
But after that the program throws this error:

```
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
	github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/application.go:244 +0x4d
panic({0x562142ff6640, 0xc000028300})
	runtime/panic.go:884 +0x212
github.com/aditya-K2/gspt/ui.(*TopTracksView).Content.func1()
	github.com/aditya-K2/gspt/ui/view_top.go:45 +0x6f3
github.com/aditya-K2/gspt/ui.(*interactiveView).update(0xc00011c400)
	github.com/aditya-K2/gspt/ui/interactive.go:231 +0x7b
github.com/aditya-K2/gspt/ui.NewInteractiveView.func1({0x10000000f?, 0x0?}, 0x0?, 0x0?, 0x0?, 0xc000005180?)
	github.com/aditya-K2/gspt/ui/interactive.go:44 +0x25
github.com/rivo/tview.(*Box).DrawForSubclass(0xc0002c6000, {0x56214302bf98, 0xc000005180}, {0x56214302aaa0?, 0xc00013a300?})
	github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/box.go:399 +0x252
github.com/rivo/tview.(*Table).Draw(0xc00013a300, {0x56214302bf98, 0xc000005180})
	github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/table.go:837 +0x56
github.com/rivo/tview.(*Flex).Draw(0xc000494720, {0x56214302bf98?, 0xc000005180})
	github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/flex.go:200 +0x3a5
github.com/rivo/tview.(*Flex).Draw(0xc0004947b0, {0x56214302bf98?, 0xc000005180})
	github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/flex.go:200 +0x3a5
github.com/rivo/tview.(*Flex).Draw(0xc000494840, {0x56214302bf98?, 0xc000005180})
	github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/flex.go:200 +0x3a5
github.com/rivo/tview.(*Pages).Draw(0xc00009f980, {0x56214302bf98, 0xc000005180})
	github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/pages.go:279 +0xda
github.com/rivo/tview.(*Application).draw(0xc00020c000)
	github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/application.go:604 +0x15a
github.com/rivo/tview.(*Application).Run(0xc00020c000)
	github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/application.go:250 +0x13e
main.main()
	github.com/aditya-K2/gspt/main.go:12 +0x31
```

My system is running the latest version of Fedora.

**Comment by aditya-K2** [comment]
I will look into this, thanks for reporting

**Comment by aditya-K2** [comment]
I will look into this, thanks for reporting
